version: '3.8'
services:
  nest-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    networks:
      - acemedia
networks:
  acemedia: